### PR TITLE
#3 filename with headers and more.

### PR DESCRIPTION
**Pull request by nocodehummel**
Fixed initial usage issues:
- filename with header and hash was invalid.
- proposal to use `__cache__` following jest naming.
- NodeJSStore not exported.
- possible circular dependency JFMCCacheContent.
- ts-jest complains about createCachingMock not a function (changed to named export).

### CODE REVIEW

**Comment by nocodehummel** [comment]
@gadicc I am facing an issue with `TypeError: Store is not a constructor`.
Searching for an answer this could be related to having the local package linked with npm. 
There are similar reports from other using `ts-jest`.
If you have the time I would appreciate a release with this PR, so I can use the released package without link.

**Comment by gadicc** [comment]
Hey @nocodehummel!  Thanks for all this.  All very sensible changes / fixes :pray:  Just a few minor comments from my side:

> ts-jest complains about createCachingMock not a function (changed to named export).

Sounds good, but does it still work if we *also* retain the default export?  This way we can retain backwards compatibility too.  Potentially we could also wrap default export with a deprecation warning, but not really a big deal.

> proposal to use __cache__ following jest naming.

Happy to make this user configurable, it should have been so anyway.  However, I'd rather retain the existing default of `./tests/fixtures/http`.  Besides for backwards compatibility, `__cache__` (for me at least) really implies temporary cache files, whereas the package (despite the possibly misleading name), is really designed not just to speed up tests but also ship the http "cache" and commit to the repo as fixtures for consistent testing.  You also sometimes see `__cache__` in things like `.gitignore` which would complicate matters.

> `constructor(location?: string) {`

Just thinking ahead here, especially since `JFMCNodeFSStore` extends `JFMCStore`.  Could we rather have the constructor take an options object, of which `location` is an optional key?

In general, again, all the changes are very sensible and well executed, so thanks again for all your efforts here :pray:  I think we're in a similar timezone, but if I don't hear back from you, I'll merge and make the above changes and publish, as I'm around this morning and I know you're waiting for this.

**Comment by gadicc** [comment]
@nocodehummel, working on this now.  I also created a new `dev` branch and merged to there, as all commits on `main` trigger a publish.

**Comment by gadicc** [comment]
@nocodehummel, closing as this is all merged.  GitHub isn't showing that because I did some rebasing by hand, but you'll see in the commit history, it's all there.  Thanks again!  Merging to main and there should be an automatic message here on the published release.

**Comment by nocodehummel** [comment]
@gadicc, thanks for the quick follow-up with a new release!
The changes are working as expected.

**Comment by gadicc** [comment]
Awesome news!  Thanks for reporting back, and sorry for my late reply.

**Pull request closed without merging**
